### ISSUE TITLE
可不可以支持一下靠变半屏，靠顶全屏显示以及对应的毛玻璃效果

### ISSUE THREAD

**Issue by xhqxhq** [FlyWM/FramelessWindow-Qt#2]
![image](https://user-images.githubusercontent.com/16683388/83468753-62fa6d80-a4b0-11ea-8ae4-36dfdea0779b.png)
![image](https://user-images.githubusercontent.com/16683388/83468818-7efe0f00-a4b0-11ea-9d64-1e7ee5e03755.png)
为知笔记支持这种效果，但是似乎没有使用重写Qt的nativeEvent，感觉您似乎比较熟悉为知笔记的源码，是否能支持这种效果

**Comment by FlyWM** [comment]
可以看下MuWinWindow这个类
